name: Changelog Generator
on:
  push:
    tags:
      - '*.*.*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          issues: false
          pullRequests: false
          compareLink: true